### FCC Numpy Practice

Hands-on code based on the FCC Data Analysis Numpy section.

In [8]:
# 1. Importing Numpy
import numpy as np  # Import the numpy library as 'np' (universal convention)

In [9]:
# 2. Array Creation Examples
arr1 = np.array([1, 2, 3, 4])          # 1D array
arr2 = np.array([[1, 2], [3, 4]])      # 2D array (matrix)
zeros = np.zeros((2, 3))               # 2 rows, 3 columns filled with 0
ones = np.ones(4)                      # 1D array of four 1s
range_arr = np.arange(0, 10, 2)        # Even numbers from 0 up to <10
print("arr1:", arr1)
print("arr2:\n", arr2)
print("zeros:\n", zeros)
print("ones:", ones)
print("range_arr:", range_arr)


arr1: [1 2 3 4]
arr2:
 [[1 2]
 [3 4]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones: [1. 1. 1. 1.]
range_arr: [0 2 4 6 8]


In [10]:
# 3. Array Types, Shapes, and Attributes
print("Shape of arr1:", arr1.shape)
print("Data type of arr2:", arr2.dtype)
print("Number of elements in arr2:", arr2.size)
print("Number of dimensions in arr2:", arr2.ndim)

Shape of arr1: (4,)
Data type of arr2: int64
Number of elements in arr2: 4
Number of dimensions in arr2: 2


In [11]:
# 4. Indexing & Slicing (1D)
print("Second and third elements of arr1:", arr1[1:3])
print("Last element of arr1:", arr1[-1])

Second and third elements of arr1: [2 3]
Last element of arr1: 4


In [17]:
# 5. Indexing (2D arrays)
print("Element at row 0, col 1 of arr2:", arr2[0, 1])
print("First column of arr2:", arr2[:, 0])  # All rows, column 0

Element at row 0, col 1 of arr2: 2
First column of arr2: [1 3]


In [16]:
# 6. Changing Shape
reshaped = arr1.reshape((2, 2))
print("Reshaped arr1 to 2x2:\n", reshaped)
flattened = arr2.flatten()
print("Flattened arr2:", flattened)

Reshaped arr1 to 2x2:
 [[  1 200]
 [  3   4]]
Flattened arr2: [1 2 3 4]


In [15]:
# 7. Mathematical Operations (elementwise)
print("arr1 + 5:", arr1 + 5)          # Adds 5 to each element
print("arr2 - 1:\n", arr2 - 1)        # Subtracts 1 from each element
print("arr1 * 2:", arr1 * 2)          # Multiplies each by 2
print("arr1 / 1.5:", arr1 / 1.5)      # Divides each by 1.5

arr1 + 5: [  6 205   8   9]
arr2 - 1:
 [[0 1]
 [2 3]]
arr1 * 2: [  2 400   6   8]
arr1 / 1.5: [  0.66666667 133.33333333   2.           2.66666667]


In [14]:
# 8. Aggregations and Statistics
print("Sum of arr1:", arr1.sum())
print("Mean of arr2:", arr2.mean())
print("Max of range_arr:", range_arr.max())
print("Standard deviation of arr1:", arr1.std())

Sum of arr1: 208
Mean of arr2: 2.5
Max of range_arr: 8
Standard deviation of arr1: 85.45466634420849


In [13]:
# 9. Boolean Indexing (Filtering)
greater_than_two = arr1 > 2
print("Mask for arr1 > 2:", greater_than_two)
print("Filtered arr1 (values > 2):", arr1[greater_than_two])

Mask for arr1 > 2: [False  True  True  True]
Filtered arr1 (values > 2): [200   3   4]


In [ ]:
# 10. Copy vs. View
arr3 = arr1.copy()   # arr3 is a new, independent array
arr3[0] = 100        # Only changes arr3
print("arr1 after arr3 modification:", arr1)
print("arr3 after arr3 modification:", arr3)

arr4 = arr1         # arr4 points to arr1's data
arr4[1] = 200
print("arr1 after arr4 modification:", arr1)  # arr1 changes
print("arr4 after arr4 modification:", arr4)

arr1 after arr3 modification: [1 2 3 4]
arr3 after arr3 modification: [100   2   3   4]
arr1 after arr4 modification: [  1 200   3   4]
arr4 after arr4 modification: [  1 200   3   4]
