### Numpy FCC Review Exercises

Practical exercises that closely follow the FreeCodeCamp curriculum to reinforce understanding.

In [1]:
# Exercise 1: Create an array of integers from 10 to 19 (inclusive)
import numpy as np
arr = np.arange(10, 20)
print("Array from 10 to 19:", arr)

Array from 10 to 19: [10 11 12 13 14 15 16 17 18 19]


In [3]:
# Exercise 2: Reshape the array to a 2x5 matrix
arr2d = arr.reshape((2, 5))
print("2x5 matrix:\n", arr2d)

2x5 matrix:
 [[10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
# Exercise 3: Select all numbers in arr greater than 14
greater_than_14 = arr[arr > 14]
print("Numbers greater than 14 in arr:", greater_than_14)

Numbers greater than 14 in arr: [15 16 17 18 19]


In [5]:
# Exercise 4: Compute the sum of arr
total_sum = arr.sum()
print("Sum of all elements in arr:", total_sum)

Sum of all elements in arr: 145


In [6]:
# Exercise 5: Set all values in arr2d greater than 15 to 0 (in-place replacement)
arr2d[arr2d > 15] = 0
print("arr2d after replacing values > 15 with 0:\n", arr2d)

arr2d after replacing values > 15 with 0:
 [[10 11 12 13 14]
 [15  0  0  0  0]]
